owner: lynot
repo: mesirve-status

skipDescriptionUpdate: false
skipTopicsUpdate: false
skipHomepageUpdate: false

sites:
  - name: App
    url: https://mesirve.app
    maxResponseTime: 60000
  - name: Admin
    url: https://admin.mesirve.app
    maxResponseTime: 60000
  - name: Api
    url: https://mesirve.app/api/client/v1/docs
    maxResponseTime: 60000
  - name: Beta Api
    url: https://beta.mesirve.app/api/client/v1/docs
    maxResponseTime: 120000

status-website:
  name: MeSirve Status
  cname: status.mesirve.app
  logoUrl: https://raw.githubusercontent.com/lynot/mesirve-status/master/assets/logo.png
  favicon: https://raw.githubusercontent.com/lynot/mesirve-status/master/assets/logo.png
  theme: night

i18n:
  footer: ""

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
